# see https://gist.github.com/sanketsudake/a089e691286bf2189bfedf295222bd43?permalink_comment_id=5623437#gistcomment-5623437
---
resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.8.0/components.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: metrics-server
      namespace: kube-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls
