[package]
name = "ningd"
version = "0.1.0"
edition = "2024"

[dependencies]
kube = { version = "1.1.0" }
k8s-openapi = { version = "0.25.0", features = ["latest"] }
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
