---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: program
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
