apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-aware-descheduler
  namespace: riset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency-aware-descheduler
  template:
    metadata:
      labels:
        app: latency-aware-descheduler
    spec:
      serviceAccountName: latency-aware-scheduler  
      restartPolicy: Always
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: k8s-master-1-vm  
      containers:
        - name: latency-descheduler
          image: adindaysafitri/scheduler:0.0.26
          imagePullPolicy: Always  
          command: ["/app/descheduler"]
          envFrom:
            - secretRef:
                name: influx-secrets
            - configMapRef:
                name: latency-scheduler-env
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: TZ
              value: "Asia/Jakarta"
            - name: RISET_NAMESPACE
              value: "riset"
            - name: PROBER_ENDPOINT
              value: "scores"
            - name: PROBER_PORT
              value: "3000"
            - name: POD_NAMESPACE
              value: "riset"
            # - name: INFLUX_BUCKET
            #   value: "resource-latency-aware-http-packets"
            # - name: EXTENDER_URL
            #   value: "http://latency-aware-extender-service:3001/score"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: descheduler-role
  namespace: riset
rules:
  # --- akses pod dasar ---
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]

  # --- eviction (core API sejak v1.32+) ---
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]

  # --- backward compatibility untuk cluster lebih lama (optional) ---
  - apiGroups: ["policy"]
    resources: ["pods/eviction"]
    verbs: ["create"]

  # --- event logging ---
  - apiGroups: ["", "events.k8s.io"]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

  # --- node info ---
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: descheduler-rolebinding
  namespace: riset
subjects:
  - kind: ServiceAccount
    name: latency-aware-scheduler
    namespace: riset
roleRef:
  kind: Role
  name: descheduler-role
  apiGroup: rbac.authorization.k8s.io
