---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: latency-aware-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: latency-aware-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-scheduler
subjects:
- kind: ServiceAccount
  name: latency-aware-scheduler
  namespace: kube-system
---
# Extra RBAC supaya scheduler bisa akses storageclass, PV, PVC dll.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: latency-aware-scheduler-extra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:volume-scheduler
subjects:
- kind: ServiceAccount
  name: latency-aware-scheduler
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: latency-aware-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: latency-aware-scheduler
        plugins:
          filter:
            enabled:
              - name: NodeResourcesFit
              - name: NodeAffinity
              - name: PodTopologySpread
              - name: TaintToleration
          score:
            # enabled:
            #   - name: NodeResourcesFit
            #   - name: NodeAffinity
            disabled:
              - name: '*'
    extenders:
      - urlPrefix: "http://latency-aware-extender-service.kube-system.svc.cluster.local:3001"
        filterVerb: "filter"
        prioritizeVerb: "prioritize"
        weight: 1
        nodeCacheCapable: true
        ignorable: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-aware-scheduler
  namespace: kube-system
  labels:
    app: latency-aware-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency-aware-scheduler
  template:
    metadata:
      labels:
        app: latency-aware-scheduler
    spec:
      serviceAccountName: latency-aware-scheduler
      nodeSelector:
          node-role.kubernetes.io/control-plane: ""
      tolerations:                        
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: kube-scheduler
        image: registry.k8s.io/kube-scheduler:v1.30.0
        command:
          - kube-scheduler
          - --config=/etc/kubernetes/scheduler/scheduler-config.yaml
          - --v=5
        volumeMounts:
          - name: scheduler-config
            mountPath: /etc/kubernetes/scheduler
      volumes:
      - name: scheduler-config
        configMap:
          name: latency-aware-scheduler-config
