---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellopod
  namespace: riset
spec:
  replicas: 9
  selector:
    matchLabels:
      app: hellopod
  template:
    metadata:
      labels:
        app: hellopod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist

      containers:
        - name: hellopod-app
          image: ghcr.io/mirzahilmi/hellopod:0.2.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
              protocol: TCP

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: POD_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          # # disabled for now, bcs i havent provide the endpoint yet
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080

          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 500Mi

          # per-container security context
          # lock down privileges inside the container
          securityContext:
            allowPrivilegeEscalation: false # prevent sudo, etc.
            privileged: false # prevent acting like host root

      terminationGracePeriodSeconds: 600

      # per-pod security context
      # enable seccomp and force non-root user
      securityContext:
        seccompProfile:
          type: RuntimeDefault # enable seccomp and the runtimes default profile

        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: hellopod-np-svc
  namespace: riset
spec:
  type: NodePort
  selector:
    app: hellopod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
      nodePort: 30_000
# ---
# apiVersion: cilium.io/v2
# kind: CiliumNetworkPolicy
# metadata:
#   name: l7-visibility
#   namespace: riset
# spec:
#   endpointSelector:
#     matchLabels:
#       "k8s:app": hellopod
#   ingress:
#     - toPorts:
#         - ports:
#             - port: "8080"
#               protocol: TCP
#           rules:
#             http: [{}]

