---
apiVersion: batch/v1
kind: Job
metadata:
  name: prober
  namespace: riset
spec:
  template:
    spec:
      containers:
        - name: prober
          image: ghcr.io/mirzahilmi/prober:0.1.1
          env:
            - name: RUST_LOG
              value: prober=debug
            - name: INTERVAL_IN_SECONDS
              value: "60"
            - name: KUBERNETES_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MQTT_HOST
              value: test.mosquitto.org
            - name: MQTT_PORT
              value: "1883"
            - name: MQTT_RESULT_TOPIC
              value: prober-0x00/result
      serviceAccountName: prober
      restartPolicy: OnFailure
  backoffLimit: 4
