---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prober
  namespace: riset
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: program
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec", "pods/attach"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: program-role-binding
subjects:
  - kind: ServiceAccount
    name: prober
    namespace: riset
roleRef:
  kind: ClusterRole
  name: program
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prober
  namespace: riset
spec:
  selector:
    matchLabels:
      name: prober-app
  template:
    metadata:
      labels:
        name: prober-app
    spec:
      serviceAccountName: prober
      containers:
        - name: prober-app
          image: ghcr.io/mirzahilmi/prober:0.2.6
          imagePullPolicy: Always

          env:
            - name: INTERVAL_IN_SECONDS
              value: "30"
            - name: RETRY_THRESHOLD
              value: "3"
            - name: PING_COUNT
              value: "5"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CILIUM_SERVICE_NAME
              value: hellopod-lb-svc

          # # disabled for now, bcs i havent provide the endpoint yet
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080

          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 250Mi
