# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.2/service.json
---
apiVersion: v1
kind: Service
metadata:
  name: hellopod-lb-svc
  namespace: riset
spec:
  type: LoadBalancer
  loadBalancerClass: "io.cilium/node"
  selector:
    app: hellopod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
