---
kubeProxyReplacement: true
# gotta enable this because prometheus helm chart cant specify loadBalancerClass
defaultLBServiceIPAM: nodeipam
nodeIPAM:
  enabled: true
image:
  pullPolicy: IfNotPresent
ipam:
  mode: kubernetes
loadBalancer:
  algorithm: maglev
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
# see https://github.com/cilium/cilium/pull/18306/files#diff-3b9bc05240342ca171cb91f803e21e841a98e3e5a22f2b631a455be9b65e0931R160-R161
bpf:
  datapathMode: lb-only
hubble:
  enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - httpV2:labelsContext=source_ip,destination_app,traffic_direction;sourceIngressContext=identity|ip
