---
config:
  theme: "neutral"
---
flowchart TD
    Proc1@{ shape: "rect", label: "Studi Literatur" } --> Proc2@{ shape: "rect", label: "Rekayasa Kebutuhan" }
    Proc2 --> Proc3@{ shape: "rect", label: "Perancangan Sistem" }
    Proc3 --> Proc4@{ shape: "rect", label: "Implementasi" }
    Proc4 --> Proc5@{ shape: "rect", label: "Pengujian dan Analisis" }
    Proc5 --> Proc6@{ shape: "rect", label: "Kesimpulan dan Saran" }
